<?php

namespace Proxies\__CG__\Abloqov\VisioplusBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Monture extends \Abloqov\VisioplusBundle\Entity\Monture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'id', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'reference', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'genre', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'prix_vente', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'stock', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'marque', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'datecreation_at', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'datemodification_at');
        }

        return array('__isInitialized__', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'id', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'reference', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'genre', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'prix_vente', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'stock', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'marque', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'datecreation_at', '' . "\0" . 'Abloqov\\VisioplusBundle\\Entity\\Monture' . "\0" . 'datemodification_at');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Monture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', array($reference));

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', array());

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', array($genre));

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', array());

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixVente($prixVente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixVente', array($prixVente));

        return parent::setPrixVente($prixVente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixVente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixVente', array());

        return parent::getPrixVente();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', array($stock));

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', array());

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque(\Abloqov\VisioplusBundle\Entity\Marque $marque = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', array($marque));

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', array());

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreationAt($datecreationAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreationAt', array($datecreationAt));

        return parent::setDatecreationAt($datecreationAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreationAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreationAt', array());

        return parent::getDatecreationAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodificationAt($datemodificationAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodificationAt', array($datemodificationAt));

        return parent::setDatemodificationAt($datemodificationAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodificationAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodificationAt', array());

        return parent::getDatemodificationAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreationAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreationAtValue', array());

        return parent::setDatecreationAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodificationAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodificationAtValue', array());

        return parent::setDatemodificationAtValue();
    }

}
